server:
  port: 9009 #网管
spring:
  application:
    name: dolphin-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server.ip}
    sentinel:
      transport:
        dashboard: ${sentinel.server.ip}
  zipkin:
    base-url: ${zipkin.server.ip}
    locator:
      discovery:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
