server:
  port: 9011
spring:
  application:
    name: dolphin-oss
management:
  endpoints:
    web:
      exposure:
        include: '*'
fdfs:
  so-timeout: 1500
  connect-timeout: 2000
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.1.95:22122
